In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [16]:
declarations = pd.read_csv("../data/raw/declarations.csv")
public_assistance = pd.read_csv("../data/raw/public_assistance.csv")

In [17]:
declarations.columns

Index(['disasterNumber', 'state', 'declarationType', 'fyDeclared',
       'incidentType', 'incidentBeginDate', 'incidentEndDate',
       'declarationDate', 'ihProgramDeclared', 'iaProgramDeclared',
       'paProgramDeclared', 'hmProgramDeclared', 'fipsStateCode',
       'fipsCountyCode', 'designatedArea'],
      dtype='str')

In [38]:
# declarations['declarationType'].unique()
# declarations['incidentType'].unique()
# dt_df.groupby("incidentType")["total_cost"].mean().sort_values(ascending=False)
dt_df.groupby("incidentType")["log_total_cost"].mean()

incidentType
Biological              8.500574
Chemical               14.309658
Coastal Storm           8.647065
Dam/Levee Break         5.832465
Drought                 0.245228
Earthquake              7.484699
Fire                    9.543784
Fishing Losses          0.000000
Flood                   4.371720
Freezing                3.883903
Human Cause             3.818164
Hurricane               9.983554
Mud/Landslide          12.799328
Other                   9.070755
Severe Ice Storm       12.002973
Severe Storm           12.676973
Snowstorm              10.789677
Straight-Line Winds     5.415134
Terrorist              15.680736
Tornado                 3.761436
Toxic Substances        3.284877
Tropical Depression    15.321387
Tropical Storm          8.057207
Tsunami                16.390247
Typhoon                 5.487516
Volcanic Eruption       5.852947
Winter Storm            8.441053
Name: log_total_cost, dtype: float64

In [46]:
dt_df = pd.read_csv("../data/processed/fema_merged_dataset.csv")
print(dt_df.shape)
dt_df.columns
# dt_df.head()
# dt_df.tail()
# dt_df.isna().sum()

(5174, 17)

Index(['disasterNumber', 'year', 'month', 'quarter', 'incident_duration_days',
       'ihProgramDeclared', 'iaProgramDeclared', 'paProgramDeclared',
       'hmProgramDeclared', 'num_counties', 'tier_very_high', 'tier_high',
       'tier_medium', 'tier_low', 'total_cost', 'log_total_cost',
       'duration_x_counties'],
      dtype='str')

In [44]:
dt = pd.read_csv("../data/processed/final_selected_features.csv")
print(dt.shape)
dt.columns

(5174, 7)

Index(['month', 'num_counties', 'incident_duration_days', 'quarter', 'year',
       'duration_x_counties', 'log_total_cost'],
      dtype='str')

In [28]:
declarations.groupby("incidentType")["total_cost"].mean().sort_values(ascending=False)

KeyError: 'Column not found: total_cost'

In [6]:
print(declarations.shape)
declarations.head()

(200, 15)

,disasterNumber,state,declarationType,fyDeclared,incidentType,incidentBeginDate,incidentEndDate,declarationDate,ihProgramDeclared,iaProgramDeclared,paProgramDeclared,hmProgramDeclared,fipsStateCode,fipsCountyCode,designatedArea
0,5626,OK,FM,2026,Fire,2026-03-19T00:00:00.000Z,NaN,2026-03-19T00:00:00.000Z,False,False,True,False,40,99,Murray (County)
1,5625,TX,FM,2026,Fire,2026-03-15T00:00:00.000Z,NaN,2026-03-15T00:00:00.000Z,False,False,True,False,48,129,Donley (County)
2,5624,OK,FM,2026,Fire,2026-03-15T00:00:00.000Z,NaN,2026-03-15T00:00:00.000Z,False,False,True,False,40,9,Beckham (County)
3,5622,SD,FM,2026,Fire,2026-03-12T00:00:00.000Z,NaN,2026-03-13T00:00:00.000Z,False,False,True,False,46,33,Custer (County)
4,5623,NE,FM,2026,Fire,2026-03-12T00:00:00.000Z,NaN,2026-03-13T00:00:00.000Z,False,False,True,False,31,47,Dawson (County)

In [4]:
declarations.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   disasterNumber     200 non-null    int64
 1   state              200 non-null    str
 2   declarationType    200 non-null    str
 3   fyDeclared         200 non-null    int64
 4   incidentType       200 non-null    str
 5   incidentBeginDate  200 non-null    str
 6   incidentEndDate    182 non-null    str
 7   declarationDate    200 non-null    str
 8   ihProgramDeclared  200 non-null    bool
 9   iaProgramDeclared  200 non-null    bool
 10  paProgramDeclared  200 non-null    bool
 11  hmProgramDeclared  200 non-null    bool
 12  fipsStateCode      200 non-null    int64
 13  fipsCountyCode     200 non-null    int64
 14  designatedArea     200 non-null    str
dtypes: bool(4), int64(4), str(7)
memory usage: 18.1 KB

In [7]:
print(public_assistance.shape)
public_assistance.head()

(200, 10)

,disasterNumber,pwNumber,projectAmount,totalObligated,federalShareObligated,damageCategoryCode,damageCategoryDescrip,projectSize,county,lastObligationDate
0,4829,1874,12576.31,12576.31,12576.31,B,Emergency Protective Measures,Small,Newberry County,2026-03-18T21:15:21.000Z
1,4899,15,67282.78,50462.09,50462.09,B,Emergency Protective Measures,Small,Alcorn County,2026-03-18T21:15:18.000Z
2,4899,25,12912.64,9684.48,9684.48,B,Emergency Protective Measures,Small,Quitman County,2026-03-18T21:15:16.000Z
3,4899,28,23853.40,17890.05,17890.05,B,Emergency Protective Measures,Small,Yalobusha County,2026-03-18T21:15:14.000Z
4,4899,21,63095.43,47321.58,47321.58,B,Emergency Protective Measures,Small,Union County,2026-03-16T23:15:25.000Z

In [8]:
public_assistance.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   disasterNumber         200 non-null    int64
 1   pwNumber               200 non-null    int64
 2   projectAmount          200 non-null    float64
 3   totalObligated         200 non-null    float64
 4   federalShareObligated  200 non-null    float64
 5   damageCategoryCode     200 non-null    str
 6   damageCategoryDescrip  200 non-null    str
 7   projectSize            200 non-null    str
 8   county                 199 non-null    str
 9   lastObligationDate     200 non-null    str
dtypes: float64(3), int64(2), str(5)
memory usage: 15.8 KB

In [14]:
# declarations.isnull().sum()
public_assistance.isnull().sum()

disasterNumber           0
pwNumber                 0
projectAmount            0
totalObligated           0
federalShareObligated    0
damageCategoryCode       0
damageCategoryDescrip    0
projectSize              0
county                   1
lastObligationDate       0
dtype: int64

In [13]:
# Summary statistics

# declarations.describe(include="all")
public_assistance.describe(include="all")

,disasterNumber,pwNumber,projectAmount,totalObligated,federalShareObligated,damageCategoryCode,damageCategoryDescrip,projectSize,county,lastObligationDate
count,200.000000,200.000000,2.000000e+02,2.000000e+02,2.000000e+02,200,200,200,199,200
unique,NaN,NaN,NaN,NaN,NaN,8,10,2,52,191
top,NaN,NaN,NaN,NaN,NaN,B,Emergency Protective Measures,Large,Statewide,2026-03-01T18:15:35.000Z
freq,NaN,NaN,NaN,NaN,NaN,49,44,122,84,2
mean,4534.115000,15964.340000,4.997269e+07,4.606051e+07,4.606049e+07,NaN,NaN,NaN,NaN,NaN
std,325.118041,33430.142926,2.783893e+08,2.545668e+08,2.545668e+08,NaN,NaN,NaN,NaN,NaN
min,1603.000000,1.000000,2.516260e+03,2.264640e+03,2.264640e+03,NaN,NaN,NaN,NaN,NaN
25%,4339.000000,1166.750000,9.145799e+04,8.579983e+04,8.579983e+04,NaN,NaN,NaN,NaN,NaN
50%,4340.000000,3580.500000,1.075212e+06,9.676907e+05,9.676907e+05,NaN,NaN,NaN,NaN,NaN
75%,4827.000000,8446.500000,8.585515e+06,7.533145e+06,7.533145e+06,NaN,NaN,NaN,NaN,NaN
max,4899.000000,108159.000000,3.001509e+09,2.701358e+09,2.701358e+09,NaN,NaN,NaN,NaN,NaN

In [19]:
# Key distributions

declarations["incidentType"].value_counts()

# public_assistance["damageCategoryCode"].value_counts()

incidentType
Winter Storm    181
Fire             18
Other             1
Name: count, dtype: int64

Some states are high-risk zones:

Florida → hurricanes

California → wildfires

Texas → floods + storms

More disasters = more total cost exposure

In [20]:
# Helps model learn:
# Which locations experience the most disasters (or claims)?
# “State = CA → higher wildfire-related cost risk”
declarations["state"].value_counts()

state
TN    86
MS    78
LA    17
OK     9
NE     5
TX     3
SD     1
DC     1
Name: count, dtype: int64

Different disasters have very different cost profiles:

. Hurricanes → massive infrastructure damage 💰💰💰

. Floods → frequent but moderate damage

. Wildfires → high but localized


Your model should learn: “If incidentType = Hurricane → expect higher cost”

In [21]:
# Disaster costs are almost always:
# Right-skewed (long tail)
# Many small events (£)
# Few extreme events (£££££)

public_assistance["projectAmount"].describe() 

# Look for:
# Mean >> Median → skewed
# Very large max values

count    2.000000e+02
mean     4.997269e+07
std      2.783893e+08
min      2.516260e+03
25%      9.145799e+04
50%      1.075212e+06
75%      8.585515e+06
max      3.001509e+09
Name: projectAmount, dtype: float64

In [ ]:
# After merge
# public_assistance.groupby("incidentType")["projectAmount"].mean()

:

In [ ]:
# Cost insights

public_assistance["projectAmount"].describe() # PROJECT AMOUNT STATS

public_assistance["federalShareObligated"].describe() # FEDERAL SHARE OBLIGATED STATS

In [ ]:
# Check duplicates

print(declarations.duplicated().sum())
print(public_assistance.duplicated().sum())

In [ ]:
# Correlation (cost drivers)

print(public_assistance.corr(numeric_only=True))